#!/usr/bin/python
# -*- coding: utf-8 -*-
#SelectUH
# Exibe um html que permite a insercao de coordenadas para consultar o banco de dados

#####Esta parte se refere a uma menu cabecalho do trabalho padrao das paginas
print 'Content-Type: text/html; charset=UTF-8\n\n'
print '<!DOCTYPE html>'
print '<html lang="en">'
print '    <head>'
print '        <meta charset="utf-8">'
print '        <meta http-equiv="X-UA-Compatible" content="IE=edge">'
print '        <meta name="viewport" content="width=device-width, initial-scale=1.0">'
print '        <meta name="description" content="Monitoramento de Aguas Superficiais - Dados de Outorga">'
print '        <meta name="author" content="Welber">'
print '        <title>Monitoramento de &Aacute;guas Superficiais - Dados de Outorga</title>'
print '        <!-- Bootstrap core CSS -->'
print '        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">'
print '        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->'
print '        <!--[if lt IE 9]>'
print '          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>'
print '          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>'
print '        <![endif]-->'
print '    </head>'
print '    <body>'
print '        <div class="container">'
print '            <table style="width: 100%;" border="0">'
print '                <tbody style="text-align: left;">'
print '                    <tr style="text-align: left; height: 20px;">'
print '                        <td style="background-color: #bfefff; text-align: center;" colspan="2" valign="middle"><span style="font-size: 10pt;"><span style="color: #006cb7;">:. Disponibilidade H&iacute;Â­drica</span></span></a><br /></td>'
print '                    </tr>'
print '                    <tr style="text-align: left;">'
print '                        <td colspan="6" valign="top">'
print '                            <p></p>'
print '                            <p style="text-align: center;"><span style="font-size: 10pt;"><strong>MONITORAMENTO DE &Aacute;GUAS SUPERFICIAIS</strong></span><br /></p>'
print '                            <p style="text-align: center;"><span style="font-size: 10pt;"><strong>Sistema de gerenciamento de outorgas</strong></span></p>'
#print '                            <span style="font-size: 8pt;"><span style="color: #006cb7;"><em><a target="_self" href="index.php?option=com_content&amp;view=article&amp;id=993:porbacias&amp;catid=81">Bacias</a></em></span></span>'
print '                        </td>'
print '                    </tr>'
print '                </tbody>'
print '            </table>'
print '            <div class="row">'
print '                <div class="col-lg-4">'
print '                    <h2>Insira as coordenadas da interferÃªncia</h2>'
print '                    <p style="text-align: justify;"></p>'
print ' 		   <p> As coordenadas devem estar em grau decimal e em SAD 69, e o separador decima deve ser ponto e n&atilde;o virgula' 
print '                    <form method="POST" action="consultaOutorga.py" role="form">'
print '                        <p>Latitude: <input type="text" class="form-control" placeholder="Informe a latitude" name="y" value="" size="2"></p>'
print '                        <p>Longitude: <input type="text" class="form-control" placeholder="Informe a longitude" name="x" value="" size="2"></p>'
print '                        <p><input type="submit" value="Enviar" class="btn btn-primary"></p>'
print '                    </form>'
print '                    <p style="text-align: justify;">Caso as coordenadas estejam em formato diferente, use a calculadora do INPE'
print ' 		   <a href= "http://www.dpi.inpe.br/calcula/"target="_blank" >Clicando aqui </a> </b></p>'
print '                </div>'
print '                <div class="col-lg-4">'
print '		   	    <p> <b> Para consultar ou alterar outorga, insira o CPF <b>' 
print '                     <form method="POST" action="alterOutorga.py" role="form">'
print '                     <p>CPF: <input type="text" class="form-control" placeholder="Informe o CPF / CNPJ" name="cpf" value="" size="2"></p>'
print '                     <p><input type="submit" value="Enviar" class="btn btn-primary"></p>'
print '			    </form>'
print '                </div>'
print '            </div>'

print '			<a href= "selectOutorgas.py">Consulta espacial de outorgas por UH</a>'
print '			<br>'
print '			<a href= "graficoOutorga.py">Grafico de disponibilidade UH</a>'
print '        </div>'
print '    </body>'
print '</html>'
